export const USER_SIGN_IN_REQUEST = 'USER_SIGN_IN_REQUEST';
export const USER_SIGN_IN_SUCCESS = 'USER_SIGN_IN_SUCCESS';
export const USER_SIGN_IN_FAILURE = 'USER_SIGN_IN_FAILITURE';
export const USER_LOGOUT = 'USER_LOGOUT';

export const IMAGE_SAVE_REQUEST = 'IMAGE_SAVE_REQUEST';
export const IMAGE_SAVE_SUCCESS = 'IMAGE_SAVE_SUCCESS';
export const IMAGE_SAVE_FAIL = 'IMAGE_SAVE_FAIL';

export const IMAGE_DELETE_REQUEST = 'IMAGE_DELETE_REQUEST';
export const IMAGE_DELETE_SUCCESS = 'IMAGE_DELETE_SUCCESS';
export const IMAGE_DELETE_FAIL = 'IMAGE_DELETE_FAIL';

export const IMAGE_LIST_REQUEST = 'IMAGE_LIST_REQUEST';
export const IMAGE_LIST_SUCCESS = 'IMAGE_LIST_SUCCESS';
export const IMAGE_LIST_FAIL = 'IMAGE_LIST_FAIL';
